### ISSUE TITLE
Question about debugging

### ISSUE THREAD

**Issue by Nurgak** [nikisalli/esp32-minecraft-server#1]
Hi @nikisalli 

I really appreciate you making this project, really excellent work!

I'd like to add some functionalities and see how much can be done on the ESP32. I'm currently [attempting](https://github.com/Nurgak/esp32-minecraft-server-arduino/tree/feature/arduino-compatible-and-procotol-update) to bring it to up to date with the latest protocol [762](https://wiki.vg/Protocol) (version 1.19.4) at the time of writing this.

I have been relatively successful, fixing one error message after another, but now I am stuck at the client displaying the message "Joining world...".

![Screenshot 2023-04-08 at 11 45 45](https://user-images.githubusercontent.com/1785126/230699985-0789b165-9c10-4222-89df-b3505f76b72d.png)
![Screenshot 2023-04-08 at 11 46 31](https://user-images.githubusercontent.com/1785126/230699989-f665727b-15f6-40a5-a7a8-f201a284c7e5.png)

I know my own attempt does not follow exactly what you have created, but I was wondering if you had any idea on how to proceed with debugging. How can I see what is preventing the client from actually displaying the game? A missing packet? Out-of-order packet? Malformed/missing data? Perhaps an example project you know of that implements the 762 protocol?

One of the challenges I had was to properly get and send the registry codec NBT, needed as part of the [Login (play)](https://wiki.vg/Protocol#Login_.28play.29) packet, previously known as [Join Game](https://wiki.vg/index.php?title=Protocol&oldid=16681#Join_Game) packet in protocol 754.

I didn't know much about the NBT format, this is how I proceeded:
* Got the compatible registry codec NBT `.dat` file from [here](https://github.com/valence-rs/valence/blob/57ee8135f6866a047cd4c794ad78d995d11551a8/extracted/registry_codec_1.19.4.dat).
* Converted to JSON with [this tool](https://github.com/midnightfreddie/nbt2json).
* Deleted most of the data to make it lighter.
* Converted it back to NBT with the same tool as above.
* Used `xxd` to get the binary.

I don't know if any of this is legal, but at least I don't get errors because of it, although it might be the reason of being stuck now...

I'm not sure where else to ask, perhaps you have some ideas?

**Comment by nikisalli** [comment]
hello!
for debugging the protocol I used wireshark to parse manually every packet but now you can use one of the many minecraft sniffers out there like https://github.com/barneygale/rex or https://github.com/adepierre/SniffCraft.

just to get things up and running quickly, I'd suggest to simply dump large NBT blocks and send them as-is to make sure the client accepts them and the problem is elsewhere. After this works you could try and compress these for memory and bandwidth saving purposes.

I've already done something similar in https://github.com/nikisalli/esp32-minecraft-server/blob/main/lib/minecraft/chunk.h with the dimension_NBT and dimension_codec_NBT by just dumping them from wireshark from a working vanilla server and sending them back from my server as-is just to make sure everything else worked.

hope this helps

**Comment by Nurgak** [comment]
I was not aware of these sniffers, I will try them out.

Thank you so much for the reply and advice, I'm sure I'll be able to get it working now 😄
